### ISSUE TITLE
I cannot deploy the contract using Truffle and Ganache

### ISSUE THREAD

**Issue by EzequielCamezzanaSimplex** [EtherBots/ETHERBOTS-Bug-Bounty#26]
I do not know if that is posible, but I could not do it.
I am working on a scanner to scan every ERC721 transaction on a blockchain, so I need to test it locally with my own blockchain.
I suspect that the reason could be that: 
> address presale = 0x84DFd9f27BcB2C7f621F373e5215094C486c545b; // RINKEBY TEST;

Every time that I would compile the contracts I get:

`Compiling ./contracts/Etherbots/AccessControl.sol...
Compiling ./contracts/Etherbots/Base.sol...
Compiling ./contracts/Etherbots/ERC721.sol...
Compiling ./contracts/Etherbots/EtherbotsAuction.sol...
Compiling ./contracts/Etherbots/EtherbotsMigrations.sol...
Compiling ./contracts/Etherbots/GenericAuction.sol...
Compiling ./contracts/Etherbots/Mint.sol...
Compiling ./contracts/Etherbots/NewCratePreSale.sol...
Compiling ./contracts/Etherbots/PerkTree.sol...
Compiling ./contracts/Etherbots/PerksRewards.sol...
Error: VM Exception while processing transaction: out of gas
    at Object.InvalidResponse (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/requestmanager.js:86:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-migrate/index.js:225:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-provider/wrapper.js:134:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/httpprovider.js:128:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:64:1)
    at XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:354:1)
    at XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:509:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/xhr2/lib/xhr2.js:469:1)
    at IncomingMessage.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:114:19)
`

**Comment by RobbieFerguson** [comment]
Hey, you'll need the non-rinkeby address! It's up on the verified etherscan.
